### ISSUE TITLE
Failed to verify API Key.

### ISSUE THREAD

**Issue by Alex-Jud** [miyoyo/syspass-browser#6]
## Expected Behavior
Connecting to an Hosting Mode SysPass installation

## Current Behavior
After having created API Authorizations in my SysPass installation, I've filled them into the "Connected Databases" like described in the Readme. After click on Connect Button, I've got the message : 

> sysPass-Browser has encountered an error:
> 
> Unable to contact sysPass, check configuration (Settings -> Connected Databases).
> Failed to verify API Key.

## Debug info

sysPass-Browser - 1.7.9
Operating system: Win64
Browser: Chrome/Chromium 99.0.4844.51

**Comment by miyoyo** [comment]
Hey, thanks for using sysPass-Browser!

This error happens when accounts cannot be listed with the provided configuration, this could mean:
 - The Link is incorrect
 - The API key is incorrect
 - The account associated with the API key has no passwords associated with it.

Can you check all three of these points?

**Comment by miyoyo** [comment]
Closed because of staleness
